apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backendsignai
deploy:
  kubectl:
    manifests:
      - deployment_db.yaml
      - deployment_back.yaml
build:
  artifacts:
    - image: signai-image
      docker:
        dockerfile: ./BackendDocker/Dockerfile
    - image: mongodb
      docker:
        dockerfile: ./DBDocker/Dockerfile
portForward:
  - resourceType: deployment
    resourceName: signai-image
    port: 80
    localPort: 8000
  - resourceType: deployment
    resourceName: signai-mongo-depl
    port: 27017
    localPort: 27017
    
