version: '3.7'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signai-mongo-depl
    restart: always
    ports:
      - 12500:27017
    volumes:
      - ./data:/data/db
volumes:
  mongo: {}